#
# .eslintrc.yml
#
# Copyright (c) 2019 Junpei Kawamoto
#
# This software is released under the MIT License.
#
# http://opensource.org/licenses/mit-license.php
#
env:
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
  - "plugin:import/recommended"
parserOptions:
  ecmaVersion: 8
  sourceType: "module"
plugins:
  - "import"
